# sudo docker-compose run --rm --service-ports bot

version: '3.9'
services:
  node:
    image: 'docker.io/bitnami/node:18'
    container_name: 'node'
    hostname: 'node'
    tty: true # Enables debugging capabilities when attached to this container.
    # command: npm install -g npm@8.15.1
    ports:
      - '3000:3000'
      - '8443:8443'
      - '63106-63108:63106-63108'
    volumes:
      - '${rootPath}/projects:/app'
      - '/tmp:/go'
    working_dir: '/app'
    environment:
      - 'TZ=Asia/Taipei'
    extra_hosts:
      - 'hostFather:${gateWay3}.1'
      - 'whitefang:${ip_whitefang}'
      - 'arena:${ip_arena}'
    networks:
      eagle:
        ipv4_address: ${gateWay3}.20
    logging:
      driver: 'local'
      options:
        max-size: '10k'
        max-file: '2'
networks:
  eagle:
    name: 'eagle'
    ipam:
      config:
      - subnet: ${gateWay3}.0/24
