version: '3.9'
services:
  adminer:
    # latest version: 4.8.1
    # sudo docker pull dehy/adminer
    image: dehy/adminer
    container_name: adminer
    restart: always
    ports:
      - 65101:80
    networks:
      appsNet:
        ipv4_address: ${gateWay3}.11
    logging:
      driver: 'local'
      options:
        max-size: '10k'
        max-file: '2'
networks:
  appsNet:
    name: appsNet
    ipam:
      config:
      - subnet: 172.16.0.0/24
