version: '3.9'
services:
  node:
    container_name: node
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/node:latest
    # command: sh -c 'npm install && npm start'
    # ports:
      # - 3000:3000
    volumes:
      - /home/apps:/app
    environment:
      - TZ=Asia/Taipei
    networks:
      appsNet:
        ipv4_address: 172.16.0.13
    logging:
      driver: 'local'
      options:
        max-size: '10k'
        max-file: '2'
networks:
  appsNet:
    external: true
    name: appsNet
