# sudo docker-compose run --rm --service-ports bot

version: '3.9'
services:
  # adminer:
  #   image: dehy/adminer # version: 4.8.1
  #   container_name: adminer
  #   hostname: adminer
  #   restart: always
  #   ports:
  #     - '64101:80'
  #   environment:
  #     - 'TZ=Asia/Taipei'
  #   networks:
  #     appsNet:
  #       ipv4_address: ${gateWay3}.11
  #   logging:
  #     driver: 'local'
  #     options:
  #       max-size: '10k'
  #       max-file: '2'
  # db:
  #   image: mariadb # version: 10.9.1-rc-jammy
  #   container_name: db
  #   hostname: db
  #   restart: always
  #   ports:
  #     - '64102:3306'
  #   volumes:
  #     - ${rootPath}/mysql/db:/var/lib/mysql
  #     - ${rootPath}/mysql/conf.d:/etc/mysql/conf.d
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=0926721122
  #     - MARIADB_USER=tzuss
  #     - MARIADB_PASSWORD=0926721122
  #     - TZ=Asia/Taipei
  #   extra_hosts:
  #     - 'hostFather:${gateWay3}.1'
  #   networks:
  #     appsNet:
  #       ipv4_address: ${gateWay3}.12
  #   logging:
  #     driver: 'local'
  #     options:
  #       max-size: '10k'
  #       max-file: '2'
  # node:
  #   image: docker.io/bitnami/node # version: 18.3.0
  #   container_name: node
  #   hostname: node
  #   tty: true # Enables debugging capabilities when attached to this container.
  #   # command: sh -c 'npm install && npm start'
  #   ports:
  #     - '64108:64108'
  #   volumes:
  #     - '${rootPath}/node:/app'
  #     - '${nginxConfig}/ssl/fullchain.pem:/app/ssl/fullchain.pem'
  #     - '${nginxConfig}/ssl/privkey.pem:/app/ssl/cert/privkey.pem'
  #   working_dir: /app
  #   environment:
  #     - TZ=Asia/Taipei
  #   extra_hosts:
  #     - 'hostFather:${gateWay3}.1'
  #   networks:
  #     appsNet:
  #       ipv4_address: ${gateWay3}.13
  #   logging:
  #     driver: 'local'
  #     options:
  #       max-size: '10k'
  #       max-file: '2'
  # nginx:
  #   image: nginx
  #   container_name: nginx
  #   hostname: nginx
  #   restart: always
  #   tty: true
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '64001:64001'
  #     - '64104:80'
  #     - '64105:443'
  #     - '64107:64107'
  #   volumes:
  #     - ${rootPath}/webs:/etc/nginx/html
  #     - ${nginxConfig}/nginx.conf:/etc/nginx/nginx.conf
  #     - ${nginxConfig}/conf.d:/etc/nginx/conf.d
  #     - ${nginxConfig}/ssl/certificate.crt:/etc/nginx/certificate.crt
  #     - ${nginxConfig}/ssl/private.key:/etc/nginx/private.key
  #     - ${nginxConfig}/ssl/fullchain.pem:/etc/nginx/fullchain.pem
  #     - ${nginxConfig}/ssl/privkey.pem:/etc/nginx/privkey.pem
  #     - TZ=Asia/Taipei
  #   extra_hosts:
  #     - 'whitefang:192.168.221.199'
  #     - 'arena:192.168.221.200'
  #     - 'hostFather:${gateWay3}.1'
  #   networks:
  #     appsNet:
  #       ipv4_address: ${gateWay3}.15
  #   logging:
  #     driver: 'local'
  #     options:
  #       max-size: '10k'
  #       max-file: '2'

  bot:
    image: 'node'
    container_name: 'bot'
    hostname: 'bot'
    ports:
      - '63107:63107'
    environment:
      - 'PORT=63107'
      - 'TZ=Asia/Taipei'
    volumes:
      - ${rootPath}/projects/bot:/apps/bot
    working_dir: /apps/bot
    extra_hosts:
      - 'hostFather:${gateWay3}.1'
      - 'whitefang:${ip_whitefang}'
      - 'arena:${ip-arena}'
    networks:
      eagle:
        ipv4_address: ${gateWay3}.21
    logging:
      driver: 'local'
      options:
        max-size: '10k'
        max-file: '2'
networks:
  eagle:
    name: 'eagle'
    ipam:
      config:
      - subnet: ${gateWay3}.0/24
